[package]
name = "configurable_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
hotwatch = "0.5"
image = "0.25"
lazy-regex = "3"
noise = "0.9"
rand = { version = "0.9", features = ["small_rng"]}
ron = "0.8"
serde = {version = "1", features = ["derive"]}
